### ISSUE TITLE
/Users/beraybentesen/Downloads/sj/third_party/sciencejournal/ios/Protos/SensorLayout.pbobjc.h:108:46: Expected ';' at end of declaration list

### ISSUE THREAD

**Issue by beraybentesen** [google/science-journal-ios#34]
### New Issue Checklist

- [x] This is an issue for the open source project, not the App Store Science Journal App
- [ ] Updated Science Journal iOS to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/google/science-journal-ios/blob/master/CONTRIBUTING.md)
- [x] I searched the forums for help [Science Journal forums](https://productforums.google.com/forum/#!forum/sciencejournal)
- [x] I searched for [existing GitHub issues](https://github.com/google/science-journal-ios/issues)

### Environment

- iOS version tested ______
- Device type (iPhone/iPad/etc) ______
- Xcode version (if applicable) ______

**Comment by beraybentesen** [comment]
/third_party/sciencejournal/ios/Protos/SensorLayout.pbobjc.h:108:46: Expected ';' at end of declaration list

**Comment by shawnmorrison** [comment]
SensorLayout.pbobjc.h is a class generated by the Protobuf library based on sensor_layout.proto. We don't control the syntax. Are you having trouble building?

**Comment by beraybentesen** [comment]
Yes, the mentioned error occurs.

**Comment by shawnmorrison** [comment]
I'm not seeing this error and I wonder if it might be an issue with your version of protobuf. Currently we only support 3.1. Can you verify your version by running `protoc --version` on the command line, and confirming it says `libprotoc 3.1.0`?

**Comment by garrettmurray** [comment]
Closing the issue for inactivity—If you're still seeing this problem, please feel free to re-open. Thanks!
