### ISSUE TITLE
Recording cell has extra padding on top edge

### ISSUE THREAD

**Issue by garrettmurray** [google/science-journal-ios#46]
When you start a recording and there's no other content in the experiment, the recording cell has extra padding on top.

**Comment by iamazhar** [comment]
Sorry for the noob question. Hasn't this bug been closed after samgrover's PR? Why is it marked Open?

**Comment by samgrover** [comment]
@iamazhar While this bug has been resolved, it wasn't with my PR mentioned above, but with an internal commit that happened a while ago. The PR was accidentally left open for a few months, until I closed it without merging a few days ago.

You can see commit that resolved this issue over here: https://github.com/google/science-journal-ios/commit/91e205e0f74a89d4b33e3cb1813cbf978bb97ec4
